name: "Release using semantic release"

inputs:
  dry_run:
    description: Enable dry-run flag on semantic-release
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.dry_run == 'false' }}
      run: npx semantic-release
      shell: bash
      env:
        GIT_AUTHOR_NAME: "Hoid"
        GIT_COMMITTER_NAME: "Hoid"
        GIT_AUTHOR_EMAIL: "hoid@zefiros.io"
        GIT_COMMITTER_EMAIL: "hoid@zefiros.io"
    - if: ${{ inputs.dry_run == 'true' }}
      run: npx semantic-release --dry-run
      shell: bash
      env:
        GIT_AUTHOR_NAME: "Hoid"
        GIT_COMMITTER_NAME: "Hoid"
        GIT_AUTHOR_EMAIL: "hoid@zefiros.io"
        GIT_COMMITTER_EMAIL: "hoid@zefiros.io"
