name: 'Release using semantic release'

runs:
  using: 'composite'
  steps:
    - run: npx semantic-release
      shell: bash
      env:
        GIT_AUTHOR_NAME: 'Hoid'
        GIT_COMMITTER_NAME: 'Hoid'
        GIT_AUTHOR_EMAIL: 'hoid@zefiros.io'
        GIT_COMMITTER_EMAIL: 'hoid@zefiros.io'
