name: Typescript Package CI

on: 
  push:
  workflow_dispatch:
      inputs:
        beta_release:
          description: Create stable release
          required: true
          type: boolean

jobs:
  typescript:
    uses: zefiros-software/node-standards/.github/workflows/reusable-typescript.yml@main
    with:
      standards_postinstall: npm link
    secrets:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: zefiros-software/node-standards/.github/workflows/reusable-build.yml@main
    secrets:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  library:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download node standards
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}
      - uses: zefiros-software/node-standards/.github/actions/setup-node@main
        with:
          working-directory: examples/library/
          global-packages: yalc
          preinstall: yalc publish --script=false && cd examples/library && yalc add @zefiros-software/node-standards
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run check:full
        working-directory: examples/library

  yargs:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download node standards
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}
      - uses: zefiros-software/node-standards/.github/actions/setup-node@main
        with:
          working-directory: examples/yargs-cli/
          global-packages: yalc
          preinstall: yalc publish --script=false && cd examples/yargs-cli && yalc add @zefiros-software/node-standards
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run check:full
        working-directory: examples/yargs-cli

  release:
    needs: [library, yargs, typescript, build]
    uses: zefiros-software/node-standards/.github/workflows/reusable-release.yml@main
    with:
      build_artifact_name: ${{ needs.build.outputs.artifact_name }}
      beta_release: ${{ inputs.beta_release || false }}
    secrets:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
